name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Get short SHA for tag
      id: sha
      run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: publish to docker hub
      uses: docker/build-push-action@v6
      with:
        tags: |
          vilkaspilka5/goapp:latest
          vilkaspilka5/goapp:${{ steps.sha.outputs.short_sha }}
